-- Get all details
SELECT * FROM v_GS_VOA_SECUREBOOTUPDATEDATA

-- Get a summary
SELECT DISTINCT UEFICA2023Status0, COUNT(UEFICA2023Status0) as Count
FROM v_GS_VOA_SECUREBOOTUPDATEDATA
GROUP BY UEFICA2023Status0;